name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Import_SQL:
    runs-on: ubuntu-latest
    name: MySQL Deploy Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: calxus/mysql-deploy-action@v1
        with:
          DATABASE_HOST: 'db.host.io'
          DATABASE_PORT: '3306'
          DATABASE_NAME: 'mydb'
          DATABASE_USERNAME: 'root'
          DATABASE_PASSWORD: 'password'
          DATABASE_SCRIPT: 'script.sql'
