name: Pipeline | DevSecOps - Heroku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
    
jobs:
  Importacion_SQL:
    uses: gtadam/mysql-deploy-action@v1
    with:
      DATABASE_HOST: 'db.host.io'
      DATABASE_PORT: '3306'
      DATABASE_NAME: 'mydb'
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: 'password'
      DATABASE_SCRIPT: 'script.sql'