name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Import_SQL:
    runs-on: ubuntu-latest
    name: MySQL Deploy Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: gtadam/mysql-deploy-action@v1
        with:
          DATABASE_HOST: 'database-testing.capjeqwtb4vf.us-east-2.rds.amazonaws.com'
          DATABASE_PORT: '3306'
          DATABASE_NAME: 'u463129590_github_actions'
          DATABASE_USERNAME: 'admin'
          DATABASE_PASSWORD: 'Ns2b7bfqbf!'
          DATABASE_SCRIPT: 'script.sql'
